INSERT INTO categoria (nombre) VALUES
    ('Electrónica'),
    ('Ropa y Accesorios'),
    ('Calzado'),
    ('Belleza y Cuidado Personal'),
    ('Hogar'),
    ('Jardín'),
    ('Deportes y Actividades al Aire Libre'),
    ('Juguetes y Juegos'),
    ('Libros y Material de Oficina'),
    ('Electrodomésticos'),
    ('Muebles'),
    ('Alimentos y Bebidas'),
    ('Automóviles y Accesorios'),
    ('Instrumentos Musicales'),
    ('Arte y Manualidades'),
    ('Electrónica de Consumo'),
    ('Salud y Bienestar'),
    ('Maletas y Equipaje'),
    ('Productos para Bebés y Niños'),
    ('Joyas y Relojes'),
    ('Electrodomésticos de Cocina'),
    ('Herramientas y Mejoras para el Hogar'),
    ('Productos para Mascotas'),
    ('Equipamiento para Negocios'),
    ('Productos para el Cuidado del Cabello'),
    ('Cámaras y Fotografía'),
    ('Equipamiento para Deportes y Fitness'),
    ('Equipos de Oficina'),
    ('Juegos de Mesa y Rompecabezas'),
    ('Suministros para Fiestas y Eventos'),
    ('Equipamiento para Viajes y Aventuras'),
    ('Productos para el Cuidado de la Piel'),
    ('Equipamiento para Acampar y Excursionismo'),
    ('Equipamiento para Actividades Acuáticas'),
    ('Electrodomésticos para la Limpieza'),
    ('Equipamiento para la Playa y Piscina'),
    ('Equipos de Sonido y Audio'),
    ('Equipamiento para Ciclismo'),
    ('Equipamiento para Deportes de Invierno'),
    ('Productos para el Cuidado de la Salud'),
    ('Equipamiento para Deportes de Raqueta'),
    ('Equipamiento para Deportes de Pelota'),
    ('Equipamiento para Deportes de Combate'),
    ('Productos para el Cuidado Oral'),
    ('Equipamiento para Deportes de Equipo'),
    ('Productos para el Cuidado de los Ojos'),
    ('Productos de Higiene Personal'),
    ('Equipamiento para Deportes de Agua'),
    ('Equipamiento para Deportes de Aventura'),
    ('Productos para el Cuidado de las Uñas'),
    ('Equipamiento para Deportes de Montaña'),
    ('Equipamiento para Deportes de Escalada'),
    ('Equipamiento para Deportes de Motor'),
    ('Productos para el Cuidado de la Barba'),
    ('Equipamiento para Deportes de Vuelo'),
    ('Equipamiento para Deportes de Tiro'),
    ('Productos de Aseo Personal'),
    ('Equipamiento para Deportes de Lucha');