INSERT INTO public.producto (es_nuevo,precio_unitario,detalle,descripcion_producto,nombre_producto,stock,calificacion) VALUES
	 (false,19530.00,'Lámpara de escritorio','Lámpara de escritorio moderna con base de madera','Lámpara de escritorio',20,4),
	 (true,519999.99,'Samsung Galaxy S23 Fe 256gb 8gb Ram Negro','Procesador y memoria RAM de 8 GB, alcanzará un alto rendimiento con gran velocidad y memoria interna de 256 GB.','Samsung Galaxy S23 Fe',50,5),
	 (false,30990.00,'Mesa auxiliar','Mesa auxiliar redonda de metal con acabado dorado','Mesa auxiliar dorada',2,3),
	 (true,569999.99,'Notebook Ryzen 7 Asus Vivobook Amd 512gb Ssd 16gb Ram','ASUS VivoBook 15 39,6 cm (15.6") Full HD AMD Ryzen 7 5800H 16 GB DDR4-SDRAM 512 GB SSD Wi-Fi 6E (802.11ax) Windows 11 Home Quiet Blue','Notebook Ryzen 7 Asus Vivobook',10,4),
	 (true,259999.00,'Smart TV LG Smart TV 43ur8750 ','Televisor LED WebOS  de 44 pulgadas con resolución 4K UHD 220V','Smart TV LG Smart TV 43ur8750',5,5),
	 (false,45000.00,'Silla de comedor','Silla de comedor moderna y ergonómica','Silla de comedor ergonómica',4,3),
	 (false,60500.00,'Mesa de centro','Mesa de centro de madera maciza con cajones de almacenamiento','Mesa de centro moderna',1,4),
	 (true,28999.00,'Parlante Philco Djp10p Portátil Con Bluetooth 220v','Altavoz Bluetooth portátil con batería de larga duración','Parlante Philco Djp10p',40,4),
	 (false,30000.00,'Auriculares inalámbricos','Auriculares inalámbricos con cancelación de ruido','AirPods Pro 2da Generación',1,5),
	 (true,13999.99,'Reloj Unisex Gadnic Alarma Cronometro Elegante Digital Color de la malla Negro','Reloj de pulsera resistente al agua con malla negra','Reloj Unisex Gadnic',30,5);

INSERT INTO categoria (id_categoria, nombre) VALUES
    (1,'Electrónica'),
    (2,'Ropa y Accesorios'),
    (3,'Calzado'),
    (4,'Belleza y Cuidado Personal'),
    (5,'Hogar'),
    (6,'Jardín'),
    (7,'Deportes y Actividades al Aire Libre'),
    (8,'Juguetes y Juegos'),
    (9,'Libros y Material de Oficina'),
    (10,'Electrodomésticos'),
    (11,'Muebles'),
    (12,'Alimentos y Bebidas'),
    (13,'Automóviles y Accesorios'),
    (14,'Instrumentos Musicales'),
    (15,'Arte y Manualidades'),
    (16,'Electrónica de Consumo'),
    (17,'Salud y Bienestar'),
    (18,'Maletas y Equipaje'),
    (19,'Productos para Bebés y Niños'),
    (20,'Joyas y Relojes'),
    (21,'Electrodomésticos de Cocina'),
    (22,'Herramientas y Mejoras para el Hogar'),
    (23,'Productos para Mascotas'),
    (24,'Equipamiento para Negocios'),
    (25,'Productos para el Cuidado del Cabello'),
    (26,'Cámaras y Fotografía'),
    (27,'Equipamiento para Deportes y Fitness'),
    (28,'Equipos de Oficina'),
    (29,'Juegos de Mesa y Rompecabezas'),
    (30,'Suministros para Fiestas y Eventos'),
    (31,'Equipamiento para Viajes y Aventuras'),
    (32,'Productos para el Cuidado de la Piel'),
    (33,'Equipamiento para Acampar y Excursionismo'),
    (34,'Equipamiento para Actividades Acuáticas'),
    (35,'Electrodomésticos para la Limpieza'),
    (36,'Equipamiento para la Playa y Piscina'),
    (37,'Equipos de Sonido y Audio'),
    (38,'Equipamiento para Ciclismo'),
    (39,'Equipamiento para Deportes de Invierno'),
    (40,'Productos para el Cuidado de la Salud'),
    (41,'Equipamiento para Deportes de Raqueta'),
    (42,'Equipamiento para Deportes de Pelota'),
    (43,'Equipamiento para Deportes de Combate'),
    (44,'Productos para el Cuidado Oral'),
    (45,'Equipamiento para Deportes de Equipo'),
    (46,'Productos para el Cuidado de los Ojos'),
    (47,'Productos de Higiene Personal'),
    (48,'Equipamiento para Deportes de Agua'),
    (49,'Equipamiento para Deportes de Aventura'),
    (50,'Productos para el Cuidado de las Uñas'),
    (51,'Equipamiento para Deportes de Montaña'),
    (52,'Equipamiento para Deportes de Escalada'),
    (53,'Equipamiento para Deportes de Motor'),
    (54,'Productos para el Cuidado de la Barba'),
    (55,'Equipamiento para Deportes de Vuelo'),
    (56,'Equipamiento para Deportes de Tiro'),
    (57,'Productos de Aseo Personal'),
    (58,'Equipamiento para Deportes de Lucha');

INSERT INTO categoria_subcategoria (tiene_categoria, es_subcategoria) VALUES
    (1,10),
    (1,16),
    (1,26),
    (1,37),
    (2,3),
    (2,20),
    (4,17),
    (4,25),
    (4,47),
    (4,50),
    (4,54),
    (4,57),
    (5,6),
    (5,11),
    (5,22),
    (7,27),
    (7,31),
    (7,33),
    (7,34),
    (7,36),
    (7,38),
    (7,39),
    (7,41),
    (7,42),
    (7,43),
    (7,45),
    (7,48),
    (7,49),
    (7,51),
    (7,52),
    (7,53),
    (7,55),
    (7,56),
    (7,58),
    (8,29),
    (9,24),
    (9,28),
    (10,21),
    (10,35),
    (17,32),
    (17,40),
    (17,44),
    (17,46);